# Generated by Django 4.0.4 on 2022-06-01 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_topic_category_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.CharField(choices=[('Web Development', 'Development'), ('Management', 'Business'), ('Economics', 'Finance & Accounting'), ('IT Certification', 'IT & Software'), ('Sports', 'Health & Fitness')], default='', max_length=200),
        ),
    ]
