# Generated by Django 4.0.4 on 2022-06-01 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_student_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='myapp.student'),
        ),
        migrations.AlterField(
            model_name='order',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='myapp.course'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(0, 'Cancelled'), (1, 'Order Confirmed')], default=1),
        ),
    ]
