# Generated by Django 4.0.4 on 2022-08-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_student_image_alter_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/images/'),
        ),
    ]
